import { getRouteMetaFromFiles } from '../core/routeMeta.js';
import { normalizePath, getRelativePath } from '../utils/index.js';
import {
  simpleLayoutId,
  filePathToRoutePath,
  linkParentChildRoutes,
  pruneEmptyLayouts,
} from './common.js';
import { DEFAULT_LAYOUT_ID } from '../constant.js';
import { FileItem } from '../types/file.js';
import { ReactRoute } from '../types/route.js';
import { ReactOptions } from '../types/options.js';
import { ResolvedRouteOptions } from '../types/resolver.js';

function generateTemplate(input: string, reactOptions?: ReactOptions) {
  return [
    '// @ts-nocheck',
    '// this file is generated by farm-plugin-auto-routes',
    `import React from 'react';`,
    '',
    `const routes = ${input};`,
    '',
    'export default routes;',
    '',
  ].join('\n');
}

function isPageFile(filePath: string) {
  return /.(t|j)sx?$/.test(filePath);
}

function isGlobalLayoutFile(filePath: string) {
  return /layouts\/index.(t|j)sx?$/.test(filePath);
}

function isInnerLayoutFile(filePath: string, dir: string) {
  return [
    `${dir}/Layout.tsx`,
    `${dir}/Layout.ts`,
    `${dir}/Layout.jsx`,
    `${dir}/Layout.js`,
  ].includes(filePath);
}

function collectLayoutIds(fileList: FileItem[]): Record<string, string> {
  const layoutIdMap: Record<string, string> = {};

  for (const { dir, files, isGlobal } of fileList) {
    for (const file of files) {
      if (isGlobalLayoutFile(file) || isInnerLayoutFile(file, dir)) {
        layoutIdMap[isGlobal ? 'global' : dir] = simpleLayoutId(dir, isGlobal);
      }
    }
  }

  return layoutIdMap;
}

function generateRouteComponent(relativePath: string, options?: ReactOptions) {
  if (options?.routerApiVersion === 'legacy') {
    return { Component: `__LAZY__React.lazy(() => import('${relativePath}'))__LAZY__` };
  }

  return {
    lazy: `__LAZY__async () => { const mod = await import('${relativePath}'); return { Component: mod.default, loader: mod.loader, action: mod.action, ErrorBoundary: mod.ErrorBoundary, handle: mod.handle, shouldRevalidate: mod.shouldRevalidate } }__LAZY__`,
  };
}

async function buildRouteMap(
  fileList: FileItem[],
  generatePath: string,
  layoutIdMap: Record<string, string>,
  reactOptions?: ReactOptions,
): Promise<Record<string, ReactRoute>> {
  const routesMap: Record<string, ReactRoute> = {};

  const filePaths = fileList.reduce((acc, { files }) => acc.concat(files), [] as string[]);
  const metadata = await getRouteMetaFromFiles(filePaths);

  for (const { dir, basePath, files } of fileList) {
    for (const file of files) {
      const isLayout = isGlobalLayoutFile(file) || isInnerLayoutFile(file, dir);
      const layoutId = layoutIdMap[dir] || layoutIdMap['global'] || DEFAULT_LAYOUT_ID;
      const routePath = isLayout
        ? normalizePath('/' + basePath)
        : filePathToRoutePath(file, dir, basePath);
      const isIndexFile = (routePath === basePath || routePath === '') && !isLayout;
      const routeId = isIndexFile
        ? layoutId
          ? `${layoutId}-index`
          : `${dir.split('/').pop()}-index`
        : routePath.slice(1).replace(/\//g, '-');
      const relativePath = getRelativePath(generatePath, file);

      let route: ReactRoute = {
        id: isLayout ? layoutId : routeId,
        path: normalizePath('/' + routePath.replace('$', ':')),
      };

      if (isLayout) {
        route.isLayout = true;
      } else {
        route.parentId = layoutId ?? null;
      }

      const routeMeta = metadata[file];
      Object.assign(route, routeMeta);
      const loading = generateRouteComponent(relativePath, reactOptions);
      Object.assign(route, loading);

      routesMap[route.id] = route;
    }
  }

  return routesMap;
}

interface ReactResolvedRouteOptions extends ResolvedRouteOptions {
  reactOptions?: ReactOptions;
}

async function getResolvedRoutes(opts: ReactResolvedRouteOptions): Promise<string> {
  const { fileList, generatePath, reactOptions } = opts;

  const layoutIdMap = collectLayoutIds(fileList);
  const routesMap = await buildRouteMap(fileList, generatePath, layoutIdMap, reactOptions);
  linkParentChildRoutes(routesMap);
  pruneEmptyLayouts(routesMap, layoutIdMap);

  return JSON.stringify(Object.values(routesMap), null, 2).replace(
    /"__LAZY__(.*?)__LAZY__"/g,
    '$1',
  );
}

export function resolveReact(reactOptions?: ReactOptions) {
  return {
    suffix: 'tsx|ts|jsx|js',
    isPageFile,
    isGlobalLayoutFile,
    generateTemplate,
    getResolvedRoutes: (options: ResolvedRouteOptions) =>
      getResolvedRoutes({
        ...options,
        reactOptions,
      }),
  };
}
