function generateTemplate(input: string) {
  return [
    '// @ts-nocheck',
    '// this file is generated by farm-plugin-auto-routes',
    '',
    `const routes = ${input};`,
    '',
    'export default routes;',
    '',
  ].join('\n');
}

function isPageFile(filePath: string): boolean {
  return /.vue$/.test(filePath);
}

function isLayoutFile(filePath: string): boolean {
  return /layouts\/index.vue$/.test(filePath);
}

export function resolveVue() {
  return {
    suffix: 'vue',
    isPageFile,
    isLayoutFile,
    generateTemplate,
  };
}
