import { linkParentChildRoutes, pruneEmptyLayouts } from '../common.js';
import { buildLayoutTree, isGlobalLayoutFile } from './layout.js';
import { buildRouteMap } from './route.js';
import type { FileItem, ResolvedRouteOptions, VueOptions } from '../../types/index.js';

function generateTemplate(input: string) {
  return [
    '// @ts-nocheck',
    '// this file is generated by farm-plugin-auto-routes',
    '',
    `const routes = ${input};`,
    '',
    'export default routes;',
    '',
  ].join('\n');
}

function isPageFile(filePath: string) {
  return /\.vue$/.test(filePath);
}

interface ReactResolvedRouteOptions extends ResolvedRouteOptions {
  vueOptions?: VueOptions;
}

async function getResolvedRoutes(opts: ReactResolvedRouteOptions): Promise<string> {
  const { fileList, generatePath, vueOptions } = opts;

  const layoutTree = buildLayoutTree(fileList as FileItem[]);

  const routesMap = await buildRouteMap(
    fileList as FileItem[],
    generatePath,
    layoutTree,
    vueOptions,
  );

  linkParentChildRoutes(routesMap);

  pruneEmptyLayouts(routesMap, layoutTree.layoutIdMap);

  return JSON.stringify(Object.values(routesMap), null, 2).replace(
    /"__LAZY__(.*?)__LAZY__"/gs,
    '$1',
  );
}

export function resolveVue(vueOptions?: VueOptions) {
  return {
    suffix: 'vue',
    isPageFile,
    isGlobalLayoutFile,
    generateTemplate,
    getResolvedRoutes: (options: ResolvedRouteOptions) =>
      getResolvedRoutes({
        ...options,
        vueOptions,
      }),
  };
}
