import { linkParentChildRoutes, pruneEmptyLayouts } from '../common.js';
import { buildLayoutTree, isGlobalLayoutFile } from '../react/layout.js';
import { buildRouteMap } from './route.js';
import type { FileItem, ReactOptions, ResolvedRouteOptions } from '../../types/index.js';

function generateTemplate(input: string, reactOptions?: ReactOptions) {
  const result = [
    '// @ts-nocheck',
    '// this file is generated by farm-plugin-auto-routes',
    '',
    `const routes = ${input};`,
    '',
    'export default routes;',
    '',
  ];

  if (reactOptions?.routerApiVersion === 'legacy') {
    result.splice(2, 0, "import React from 'react';");
  }

  return result.join('\n');
}

function isPageFile(filePath: string) {
  return /\.(t|j)sx?$/.test(filePath);
}

interface ReactResolvedRouteOptions extends ResolvedRouteOptions {
  reactOptions?: ReactOptions;
}

async function getResolvedRoutes(opts: ReactResolvedRouteOptions): Promise<string> {
  const { fileList, generatePath, reactOptions } = opts;

  const layoutTree = buildLayoutTree(fileList as FileItem[]);

  const routesMap = await buildRouteMap(
    fileList as FileItem[],
    generatePath,
    layoutTree,
    reactOptions,
  );

  linkParentChildRoutes(routesMap);

  pruneEmptyLayouts(routesMap, layoutTree.layoutIdMap);

  return JSON.stringify(Object.values(routesMap), null, 2).replace(
    /"__LAZY__(.*?)__LAZY__"/gs,
    '$1',
  );
}

export function resolveReact(reactOptions?: ReactOptions) {
  return {
    suffix: 'tsx|ts|jsx|js',
    isPageFile,
    isGlobalLayoutFile,
    generateTemplate: (input: string) => generateTemplate(input, reactOptions),
    getResolvedRoutes: (options: ResolvedRouteOptions) =>
      getResolvedRoutes({
        ...options,
        reactOptions,
      }),
  };
}
