export function generateRouterTemplate(routes: string): string {
  return `// @ts-nocheck
// this file is generated by farm-plugin-auto-routes
import React from 'react';

const routes = ${routes};

export default routes;
`;
}
