export function generateRouterTemplate(
  routes: string[],
  routeComponents: string[]
): string {
  return `// @ts-nocheck
// this file is generated by farm-plugin-auto-routes
// do not change anytime!
import React, { Suspense } from 'react';

function withLazyLoad(LazyComponent) {
  return (props) => (
    <Suspense fallback={props.loadingComponent}>
      <LazyComponent />
    </Suspense>
  );
}

export function getRoutes() {
  const routes = {${routes.join(',')}};
  return {
    routes,
    routeComponents: {
${routeComponents.join(',\n')}
    },
  };
}
  `;
}
